name: Make release & publish Docker image

on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    name: Build and push the Docker image
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: ghcr.io/yukitsune/muse:${{ github.sha }}
        
    steps:
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build \
          --file Dockerfile \
          --build-arg COMMIT_HASH=${{ github.sha }} \
          --build-arg BUILD_DATE=${{ steps.current-time.outputs.time }} \
          .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.12.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}
